/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SessionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "session";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type NavItem = {
  _type: "navItem";
  title?: string;
  linkType: "route" | "page" | "external";
  route?:
    | "/schedule"
    | "/speakers"
    | "/sponsors"
    | "/venue"
    | "/cfp"
    | "/announcements";
  page?: PageReference | SessionReference | PersonReference;
  url?: string;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type FaqSection = {
  _type: "faqSection";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type CtaBlock = {
  _type: "ctaBlock";
  heading: string;
  body?: string;
  cta: Cta;
};

export type SchedulePreview = {
  _type: "schedulePreview";
  heading?: string;
  day?: string;
  maxSlots?: number;
};

export type SponsorBar = {
  _type: "sponsorBar";
  heading?: string;
  tiers?: Array<string>;
};

export type SpeakerGrid = {
  _type: "speakerGrid";
  heading?: string;
  speakers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  limit?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = {
  _type: "richText";
  heading?: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type Hero = {
  _type: "hero";
  heading: string;
  subheading?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cta?: Cta;
};

export type Cta = {
  _type: "cta";
  label: string;
  linkType?: "internal" | "external";
  internalLink?: PageReference | SessionReference | PersonReference;
  externalUrl?: string;
  style?: "primary" | "secondary" | "ghost";
};

export type ChatState = {
  _id: string;
  _type: "chat.state";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "subscription" | "lock" | "cache" | "list";
  threadId?: string;
  lockToken?: string;
  expiresAt?: number;
  value?: string;
  items?: Array<string>;
};

export type AgentConversation = {
  _id: string;
  _type: "agent.conversation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: "telegram" | "whatsapp" | "web";
  summary?: string;
  messages?: Array<{
    role?: string;
    content?: string;
    _key: string;
  }>;
  classification?: {
    successRate?: number;
    agentConfusion?: number;
    userConfusion?: number;
  };
  contentGap?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?:
    | "general"
    | "venue"
    | "schedule"
    | "registration"
    | "accessibility"
    | "conduct"
    | "speakers";
};

export type Prompt = {
  _id: string;
  _type: "prompt";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  instruction: string;
  description?: string;
};

export type SubmissionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "submission";
};

export type EmailLog = {
  _id: string;
  _type: "emailLog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  resendId?: string;
  template?: string;
  to?: string;
  subject?: string;
  sentAt?: string;
  status?: "sent" | "delivered" | "bounced" | "failed" | "complained";
  relatedDocument?: SubmissionReference | PersonReference;
};

export type EmailTemplate = {
  _id: string;
  _type: "emailTemplate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  subject: string;
  body: Array<{
    children?: Array<
      | {
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }
      | {
          variableKey: string;
          _type: "pteInterpolationVariable";
          _key: string;
        }
    >;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  audience?: "all-attendees" | "speakers" | "sponsors" | "submitters";
  trigger?:
    | "manual"
    | "on-submission-received"
    | "on-submission-accepted"
    | "on-submission-rejected"
    | "on-speaker-confirmed"
    | "scheduled";
  status?: "draft" | "active" | "archived";
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ConferenceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "conference";
};

export type Submission = {
  _id: string;
  _type: "submission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sessionTitle: string;
  sessionType: "talk" | "lightning" | "panel" | "workshop";
  abstract: string;
  level: "beginner" | "intermediate" | "advanced";
  topics?: Array<string>;
  submitterName: string;
  submitterEmail: string;
  company?: string;
  bio: string;
  status?:
    | "submitted"
    | "screening"
    | "scored"
    | "in-review"
    | "accepted"
    | "rejected"
    | "withdrawn";
  submittedAt?: string;
  aiScreening?: {
    score?: number;
    summary?: string;
    scoredAt?: string;
  };
  reviewNotes?: string;
  conference?: ConferenceReference;
};

export type VenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "venue";
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body: string;
  links?: Array<
    | {
        label: string;
        url: string;
        _type: "externalLink";
        _key: string;
      }
    | {
        label: string;
        reference: SessionReference | PersonReference | VenueReference;
        _type: "internalLink";
        _key: string;
      }
  >;
  status?: "draft" | "ready" | "published";
  publishedAt?: string;
  distributionLog?: Array<{
    channel?: string;
    sentAt?: string;
    status?: string;
    details?: string;
    _type: "logEntry";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & SpeakerGrid)
    | ({
        _key: string;
      } & SponsorBar)
    | ({
        _key: string;
      } & SchedulePreview)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & FaqSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  tier: "platinum" | "gold" | "silver" | "bronze" | "community";
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  website?: string;
  order?: number;
};

export type RoomReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "room";
};

export type ScheduleSlot = {
  _id: string;
  _type: "scheduleSlot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  session: SessionReference;
  conference: ConferenceReference;
  startTime: string;
  endTime: string;
  room: RoomReference;
  isPlenary?: boolean;
};

export type Room = {
  _id: string;
  _type: "room";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  venue: VenueReference;
  capacity?: number;
  floor?: string;
  amenities?: Array<string>;
  order?: number;
};

export type TrackReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "track";
};

export type Session = {
  _id: string;
  _type: "session";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sessionType:
    | "keynote"
    | "talk"
    | "panel"
    | "workshop"
    | "lightning"
    | "break"
    | "social";
  abstract?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  track?: TrackReference;
  level?: "beginner" | "intermediate" | "advanced";
  duration: number;
  speakers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  moderator?: PersonReference;
  capacity?: number;
  prerequisites?: string;
  materials?: Array<{
    title: string;
    url: string;
    type?: "repo" | "slides" | "docs" | "other";
    _type: "material";
    _key: string;
  }>;
  slidesUrl?: string;
  recordingUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Track = {
  _id: string;
  _type: "track";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  color?: Color;
  order?: number;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role: string;
  company?: string;
  email?: string;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  twitter?: string;
  github?: string;
  linkedin?: string;
  website?: string;
  telegramId?: string;
  travelStatus?: "not-started" | "in-progress" | "booked" | "local";
  internalNotes?: string;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Conference = {
  _id: string;
  _type: "conference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  tagline?: string;
  description: string;
  startDate: string;
  endDate: string;
  venue?: VenueReference;
  tracks?: Array<
    {
      _key: string;
    } & TrackReference
  >;
  organizers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  socialCard?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cfpOpen?: boolean;
  cfpDeadline?: string;
  cfpGuidelines?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  scoringCriteria?: string;
  registrationUrl?: string;
  registrationLabel?: string;
  socialLinks?: {
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    instagram?: string;
    mastodon?: string;
  };
  headerNav?: Array<
    {
      _key: string;
    } & NavItem
  >;
  footerNav?: Array<
    {
      _key: string;
    } & NavItem
  >;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  address: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  mapUrl?: string;
  transitInfo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  wifiInfo?: {
    network?: string;
    password?: string;
  };
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  name?: string;
  slug: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | SessionReference
  | PersonReference
  | NavItem
  | FaqReference
  | FaqSection
  | CtaBlock
  | SchedulePreview
  | SponsorBar
  | SpeakerGrid
  | SanityImageAssetReference
  | RichText
  | Hero
  | Cta
  | ChatState
  | AgentConversation
  | Faq
  | Prompt
  | SubmissionReference
  | EmailLog
  | EmailTemplate
  | Slug
  | ConferenceReference
  | Submission
  | VenueReference
  | Announcement
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Sponsor
  | RoomReference
  | ScheduleSlot
  | Room
  | TrackReference
  | Session
  | Track
  | Color
  | Person
  | Conference
  | Venue
  | SanityAgentContext
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../packages/sanity-queries/src/announcements.ts
// Variable: ANNOUNCEMENTS_QUERY
// Query: *[_type == "announcement" && status == "published"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    body  }
export type ANNOUNCEMENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string | null;
  body: string;
}>;

// Source: ../../packages/sanity-queries/src/announcements.ts
// Variable: ANNOUNCEMENT_DETAIL_QUERY
// Query: *[_type == "announcement" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    publishedAt,    body,    links[] {      _type,      label,      url,      reference-> {        _type,        "slug": slug.current,        "name": coalesce(title, name)      }    }  }
export type ANNOUNCEMENT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  publishedAt: string | null;
  body: string;
  links: Array<
    | {
        _type: "externalLink";
        label: string;
        url: string;
        reference: null;
      }
    | {
        _type: "internalLink";
        label: string;
        url: null;
        reference:
          | {
              _type: "person";
              slug: string;
              name: string;
            }
          | {
              _type: "session";
              slug: string;
              name: string;
            }
          | {
              _type: "venue";
              slug: string;
              name: string;
            };
      }
  > | null;
} | null;

// Source: ../../packages/sanity-queries/src/announcements.ts
// Variable: ANNOUNCEMENT_SLUGS_QUERY
// Query: *[_type == "announcement" && status == "published" && defined(slug.current)]{ "slug": slug.current }
export type ANNOUNCEMENT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../../packages/sanity-queries/src/conference.ts
// Variable: CFP_CONFIG_QUERY
// Query: *[_type == "conference"][0]{    _id,    name,    cfpOpen,    cfpDeadline,    cfpGuidelines  }
export type CFP_CONFIG_QUERY_RESULT = {
  _id: string;
  name: string;
  cfpOpen: boolean | null;
  cfpDeadline: string | null;
  cfpGuidelines: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../../packages/sanity-queries/src/conference.ts
// Variable: CONFERENCE_QUERY
// Query: *[_type == "conference"][0]{    _id,    name,    "slug": slug.current,    tagline,    description,    startDate,    endDate,    venue->{      _id,      name,      address    },    tracks[]->{      _id,      name,      "slug": slug.current,      color    },    logo { ..., alt },    socialCard  }
export type CONFERENCE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  tagline: string | null;
  description: string;
  startDate: string;
  endDate: string;
  venue: {
    _id: string;
    name: string;
    address: string;
  } | null;
  tracks: Array<{
    _id: string;
    name: string;
    slug: string;
    color: Color | null;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  socialCard: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: ../../packages/sanity-queries/src/navigation.ts
// Variable: NAV_QUERY
// Query: *[_type == "conference"][0]{    name,    logo { ..., alt },    registrationUrl,    registrationLabel,    socialLinks,    headerNav[] {      _key, title, linkType,      page->{ _type, title, "slug": slug.current },      route, url    },    footerNav[] {      _key, title, linkType,      page->{ _type, title, "slug": slug.current },      route, url    }  }
export type NAV_QUERY_RESULT = {
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  registrationUrl: string | null;
  registrationLabel: string | null;
  socialLinks: {
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    instagram?: string;
    mastodon?: string;
  } | null;
  headerNav: Array<{
    _key: string;
    title: string | null;
    linkType: "external" | "page" | "route";
    page:
      | {
          _type: "page";
          title: string;
          slug: string;
        }
      | {
          _type: "person";
          title: null;
          slug: string;
        }
      | {
          _type: "session";
          title: string;
          slug: string;
        }
      | null;
    route:
      | "/announcements"
      | "/cfp"
      | "/schedule"
      | "/speakers"
      | "/sponsors"
      | "/venue"
      | null;
    url: string | null;
  }> | null;
  footerNav: Array<{
    _key: string;
    title: string | null;
    linkType: "external" | "page" | "route";
    page:
      | {
          _type: "page";
          title: string;
          slug: string;
        }
      | {
          _type: "person";
          title: null;
          slug: string;
        }
      | {
          _type: "session";
          title: string;
          slug: string;
        }
      | null;
    route:
      | "/announcements"
      | "/cfp"
      | "/schedule"
      | "/speakers"
      | "/sponsors"
      | "/venue"
      | null;
    url: string | null;
  }> | null;
} | null;

// Source: ../../packages/sanity-queries/src/pages.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    sections[] {      _key,      _type,      _type == "hero" => {        heading,        subheading,        backgroundImage { ..., alt },        cta { label, linkType, style, externalUrl, internalLink->{ _type, "slug": slug.current } }      },      _type == "richText" => {        heading,        content[] { ... }      },      _type == "speakerGrid" => {        heading,        limit,        speakers[]->{ _id, name, "slug": slug.current, role, photo { ..., alt } }      },      _type == "sponsorBar" => {        heading,        tiers      },      _type == "schedulePreview" => {        heading,        day,        maxSlots      },      _type == "ctaBlock" => {        heading,        body,        cta { label, linkType, style, externalUrl, internalLink->{ _type, "slug": slug.current } }      },      _type == "faqSection" => {        heading,        items[] { _key, question, answer }      }    },    seoTitle,    seoDescription,    ogImage  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  sections: Array<
    | {
        _key: string;
        _type: "ctaBlock";
        heading: string;
        body: string | null;
        cta: {
          label: string;
          linkType: "external" | "internal" | null;
          style: "ghost" | "primary" | "secondary" | null;
          externalUrl: string | null;
          internalLink:
            | {
                _type: "page";
                slug: string;
              }
            | {
                _type: "person";
                slug: string;
              }
            | {
                _type: "session";
                slug: string;
              }
            | null;
        };
      }
    | {
        _key: string;
        _type: "faqSection";
        heading: string | null;
        items: Array<{
          _key: string;
          question: null;
          answer: null;
        }> | null;
      }
    | {
        _key: string;
        _type: "hero";
        heading: string;
        subheading: string | null;
        backgroundImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
        } | null;
        cta: {
          label: string;
          linkType: "external" | "internal" | null;
          style: "ghost" | "primary" | "secondary" | null;
          externalUrl: string | null;
          internalLink:
            | {
                _type: "page";
                slug: string;
              }
            | {
                _type: "person";
                slug: string;
              }
            | {
                _type: "session";
                slug: string;
              }
            | null;
        } | null;
      }
    | {
        _key: string;
        _type: "richText";
        heading: string | null;
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?:
                | "blockquote"
                | "h1"
                | "h2"
                | "h3"
                | "h4"
                | "h5"
                | "h6"
                | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
      }
    | {
        _key: string;
        _type: "schedulePreview";
        heading: string | null;
        day: string | null;
        maxSlots: number | null;
      }
    | {
        _key: string;
        _type: "speakerGrid";
        heading: string | null;
        limit: number | null;
        speakers: Array<{
          _id: string;
          name: string;
          slug: string;
          role: string;
          photo: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: "image";
          };
        }> | null;
      }
    | {
        _key: string;
        _type: "sponsorBar";
        heading: string | null;
        tiers: Array<string> | null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: ../../packages/sanity-queries/src/pages.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{ "slug": slug.current }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../../packages/sanity-queries/src/people.ts
// Variable: SPEAKERS_QUERY
// Query: *[_type == "person"] | order(name asc) {    _id,    name,    "slug": slug.current,    photo { ..., alt },    role,    company,    "sessionCount": count(*[_type == "session" && references(^._id)])  }
export type SPEAKERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role: string;
  company: string | null;
  sessionCount: number;
}>;

// Source: ../../packages/sanity-queries/src/people.ts
// Variable: SPEAKER_DETAIL_QUERY
// Query: *[_type == "person" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    photo { ..., alt },    role,    company,    bio,    twitter,    github,    linkedin,    website,    seoTitle,    seoDescription,    ogImage,    "sessions": *[_type == "session" && references(^._id)] {      _id,      title,      "slug": slug.current,      sessionType,      level,      track->{ name, "slug": slug.current, color },      "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {        startTime,        endTime,        room->{ name, "slug": slug.current }      }    }  }
export type SPEAKER_DETAIL_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role: string;
  company: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  twitter: string | null;
  github: string | null;
  linkedin: string | null;
  website: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  sessions: Array<{
    _id: string;
    title: string;
    slug: string;
    sessionType:
      | "break"
      | "keynote"
      | "lightning"
      | "panel"
      | "social"
      | "talk"
      | "workshop";
    level: "advanced" | "beginner" | "intermediate" | null;
    track: {
      name: string;
      slug: string;
      color: Color | null;
    } | null;
    slot: {
      startTime: string;
      endTime: string;
      room: {
        name: string;
        slug: string;
      };
    } | null;
  }>;
} | null;

// Source: ../../packages/sanity-queries/src/people.ts
// Variable: SPEAKER_SLUGS_QUERY
// Query: *[_type == "person" && defined(slug.current)]{ "slug": slug.current }
export type SPEAKER_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../../packages/sanity-queries/src/schedule.ts
// Variable: SCHEDULE_DAY_QUERY
// Query: *[_type == "scheduleSlot"    && conference._ref == $conferenceId    && startTime >= $dayStart    && startTime < $dayEnd  ] | order(startTime asc) {    _id,    startTime,    endTime,    isPlenary,    room->{      _id,      name,      "slug": slug.current,      capacity,      floor    },    session->{      _id,      title,      "slug": slug.current,      sessionType,      level,      duration,      track->{        _id,        name,        "slug": slug.current,        color      },      speakers[]->{        _id,        name,        "slug": slug.current,        photo { ..., alt },        role,        company      },      moderator->{        _id,        name,        "slug": slug.current      }    }  }
export type SCHEDULE_DAY_QUERY_RESULT = Array<{
  _id: string;
  startTime: string;
  endTime: string;
  isPlenary: boolean | null;
  room: {
    _id: string;
    name: string;
    slug: string;
    capacity: number | null;
    floor: string | null;
  };
  session: {
    _id: string;
    title: string;
    slug: string;
    sessionType:
      | "break"
      | "keynote"
      | "lightning"
      | "panel"
      | "social"
      | "talk"
      | "workshop";
    level: "advanced" | "beginner" | "intermediate" | null;
    duration: number;
    track: {
      _id: string;
      name: string;
      slug: string;
      color: Color | null;
    } | null;
    speakers: Array<{
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      };
      role: string;
      company: string | null;
    }> | null;
    moderator: {
      _id: string;
      name: string;
      slug: string;
    } | null;
  };
}>;

// Source: ../../packages/sanity-queries/src/sessions.ts
// Variable: SESSION_DETAIL_QUERY
// Query: *[_type == "session" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    sessionType,    level,    duration,    abstract,    track->{ _id, name, "slug": slug.current, color },    speakers[]->{      _id,      name,      "slug": slug.current,      photo { ..., alt },      role,      company    },    moderator->{      _id,      name,      "slug": slug.current,      photo { ..., alt },      role,      company    },    capacity,    prerequisites,    materials[] { title, url, type },    slidesUrl,    recordingUrl,    seoTitle,    seoDescription,    ogImage,    "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {      startTime,      endTime,      room->{ name, "slug": slug.current, floor }    }  }
export type SESSION_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  sessionType:
    | "break"
    | "keynote"
    | "lightning"
    | "panel"
    | "social"
    | "talk"
    | "workshop";
  level: "advanced" | "beginner" | "intermediate" | null;
  duration: number;
  abstract: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  track: {
    _id: string;
    name: string;
    slug: string;
    color: Color | null;
  } | null;
  speakers: Array<{
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    role: string;
    company: string | null;
  }> | null;
  moderator: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    role: string;
    company: string | null;
  } | null;
  capacity: number | null;
  prerequisites: string | null;
  materials: Array<{
    title: string;
    url: string;
    type: "docs" | "other" | "repo" | "slides" | null;
  }> | null;
  slidesUrl: string | null;
  recordingUrl: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slot: {
    startTime: string;
    endTime: string;
    room: {
      name: string;
      slug: string;
      floor: string | null;
    };
  } | null;
} | null;

// Source: ../../packages/sanity-queries/src/sessions.ts
// Variable: SESSIONS_SUMMARY_QUERY
// Query: *[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])] | order(title asc) {    _id,    title,    "slug": slug.current,    sessionType  }
export type SESSIONS_SUMMARY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  sessionType:
    | "break"
    | "keynote"
    | "lightning"
    | "panel"
    | "social"
    | "talk"
    | "workshop";
}>;

// Source: ../../packages/sanity-queries/src/sessions.ts
// Variable: SESSIONS_LISTING_QUERY
// Query: *[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])] | order(title asc) {    _id,    title,    "slug": slug.current,    sessionType,    level,    duration,    track->{ _id, name, "slug": slug.current, color },    speakers[]->{      _id,      name,      "slug": slug.current,      photo { ..., alt }    },    "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {      startTime,      room->{ name, "slug": slug.current }    }  }
export type SESSIONS_LISTING_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  sessionType:
    | "break"
    | "keynote"
    | "lightning"
    | "panel"
    | "social"
    | "talk"
    | "workshop";
  level: "advanced" | "beginner" | "intermediate" | null;
  duration: number;
  track: {
    _id: string;
    name: string;
    slug: string;
    color: Color | null;
  } | null;
  speakers: Array<{
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  }> | null;
  slot: {
    startTime: string;
    room: {
      name: string;
      slug: string;
    };
  } | null;
}>;

// Source: ../../packages/sanity-queries/src/sessions.ts
// Variable: SESSION_SLUGS_QUERY
// Query: *[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])]{ "slug": slug.current }
export type SESSION_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../../packages/sanity-queries/src/sponsors.ts
// Variable: SPONSORS_QUERY
// Query: *[_type == "sponsor"] | order(    select(      tier == "platinum" => 0,      tier == "gold" => 1,      tier == "silver" => 2,      tier == "bronze" => 3,      tier == "community" => 4,      5    ) asc,    order asc,    name asc  ) {    _id,    name,    "slug": slug.current,    tier,    logo { ..., alt },    description,    website  }
export type SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  tier: "bronze" | "community" | "gold" | "platinum" | "silver";
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  website: string | null;
}>;

// Source: ../../packages/sanity-queries/src/venue.ts
// Variable: VENUE_QUERY
// Query: *[_type == "conference"][0].venue->{    _id,    name,    "slug": slug.current,    address,    description,    mapUrl,    transitInfo,    wifiInfo,    image { ..., alt },    "rooms": *[_type == "room" && venue._ref == ^._id] | order(order asc, name asc) {      _id,      name,      "slug": slug.current,      floor,      capacity,      amenities    }  }
export type VENUE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  address: string;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  mapUrl: string | null;
  transitInfo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  wifiInfo: {
    network?: string;
    password?: string;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  rooms: Array<{
    _id: string;
    name: string;
    slug: string;
    floor: string | null;
    capacity: number | null;
    amenities: Array<string> | null;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "announcement" && status == "published"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    body\n  }': ANNOUNCEMENTS_QUERY_RESULT;
    '*[_type == "announcement" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    body,\n    links[] {\n      _type,\n      label,\n      url,\n      reference-> {\n        _type,\n        "slug": slug.current,\n        "name": coalesce(title, name)\n      }\n    }\n  }': ANNOUNCEMENT_DETAIL_QUERY_RESULT;
    '*[_type == "announcement" && status == "published" && defined(slug.current)]{ "slug": slug.current }': ANNOUNCEMENT_SLUGS_QUERY_RESULT;
    '*[_type == "conference"][0]{\n    _id,\n    name,\n    cfpOpen,\n    cfpDeadline,\n    cfpGuidelines\n  }': CFP_CONFIG_QUERY_RESULT;
    '*[_type == "conference"][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    description,\n    startDate,\n    endDate,\n    venue->{\n      _id,\n      name,\n      address\n    },\n    tracks[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      color\n    },\n    logo { ..., alt },\n    socialCard\n  }': CONFERENCE_QUERY_RESULT;
    '*[_type == "conference"][0]{\n    name,\n    logo { ..., alt },\n    registrationUrl,\n    registrationLabel,\n    socialLinks,\n    headerNav[] {\n      _key, title, linkType,\n      page->{ _type, title, "slug": slug.current },\n      route, url\n    },\n    footerNav[] {\n      _key, title, linkType,\n      page->{ _type, title, "slug": slug.current },\n      route, url\n    }\n  }': NAV_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    sections[] {\n      _key,\n      _type,\n      _type == "hero" => {\n        heading,\n        subheading,\n        backgroundImage { ..., alt },\n        cta { label, linkType, style, externalUrl, internalLink->{ _type, "slug": slug.current } }\n      },\n      _type == "richText" => {\n        heading,\n        content[] { ... }\n      },\n      _type == "speakerGrid" => {\n        heading,\n        limit,\n        speakers[]->{ _id, name, "slug": slug.current, role, photo { ..., alt } }\n      },\n      _type == "sponsorBar" => {\n        heading,\n        tiers\n      },\n      _type == "schedulePreview" => {\n        heading,\n        day,\n        maxSlots\n      },\n      _type == "ctaBlock" => {\n        heading,\n        body,\n        cta { label, linkType, style, externalUrl, internalLink->{ _type, "slug": slug.current } }\n      },\n      _type == "faqSection" => {\n        heading,\n        items[] { _key, question, answer }\n      }\n    },\n    seoTitle,\n    seoDescription,\n    ogImage\n  }': PAGE_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{ "slug": slug.current }': PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "person"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    photo { ..., alt },\n    role,\n    company,\n    "sessionCount": count(*[_type == "session" && references(^._id)])\n  }': SPEAKERS_QUERY_RESULT;
    '*[_type == "person" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    photo { ..., alt },\n    role,\n    company,\n    bio,\n    twitter,\n    github,\n    linkedin,\n    website,\n    seoTitle,\n    seoDescription,\n    ogImage,\n    "sessions": *[_type == "session" && references(^._id)] {\n      _id,\n      title,\n      "slug": slug.current,\n      sessionType,\n      level,\n      track->{ name, "slug": slug.current, color },\n      "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {\n        startTime,\n        endTime,\n        room->{ name, "slug": slug.current }\n      }\n    }\n  }': SPEAKER_DETAIL_QUERY_RESULT;
    '*[_type == "person" && defined(slug.current)]{ "slug": slug.current }': SPEAKER_SLUGS_QUERY_RESULT;
    '*[_type == "scheduleSlot"\n    && conference._ref == $conferenceId\n    && startTime >= $dayStart\n    && startTime < $dayEnd\n  ] | order(startTime asc) {\n    _id,\n    startTime,\n    endTime,\n    isPlenary,\n    room->{\n      _id,\n      name,\n      "slug": slug.current,\n      capacity,\n      floor\n    },\n    session->{\n      _id,\n      title,\n      "slug": slug.current,\n      sessionType,\n      level,\n      duration,\n      track->{\n        _id,\n        name,\n        "slug": slug.current,\n        color\n      },\n      speakers[]->{\n        _id,\n        name,\n        "slug": slug.current,\n        photo { ..., alt },\n        role,\n        company\n      },\n      moderator->{\n        _id,\n        name,\n        "slug": slug.current\n      }\n    }\n  }': SCHEDULE_DAY_QUERY_RESULT;
    '*[_type == "session" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    sessionType,\n    level,\n    duration,\n    abstract,\n    track->{ _id, name, "slug": slug.current, color },\n    speakers[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo { ..., alt },\n      role,\n      company\n    },\n    moderator->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo { ..., alt },\n      role,\n      company\n    },\n    capacity,\n    prerequisites,\n    materials[] { title, url, type },\n    slidesUrl,\n    recordingUrl,\n    seoTitle,\n    seoDescription,\n    ogImage,\n    "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {\n      startTime,\n      endTime,\n      room->{ name, "slug": slug.current, floor }\n    }\n  }': SESSION_DETAIL_QUERY_RESULT;
    '*[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    sessionType\n  }': SESSIONS_SUMMARY_QUERY_RESULT;
    '*[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    sessionType,\n    level,\n    duration,\n    track->{ _id, name, "slug": slug.current, color },\n    speakers[]->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo { ..., alt }\n    },\n    "slot": *[_type == "scheduleSlot" && session._ref == ^._id][0] {\n      startTime,\n      room->{ name, "slug": slug.current }\n    }\n  }': SESSIONS_LISTING_QUERY_RESULT;
    '*[_type == "session" && defined(slug.current) && !(sessionType in ["break", "social"])]{ "slug": slug.current }': SESSION_SLUGS_QUERY_RESULT;
    '*[_type == "sponsor"] | order(\n    select(\n      tier == "platinum" => 0,\n      tier == "gold" => 1,\n      tier == "silver" => 2,\n      tier == "bronze" => 3,\n      tier == "community" => 4,\n      5\n    ) asc,\n    order asc,\n    name asc\n  ) {\n    _id,\n    name,\n    "slug": slug.current,\n    tier,\n    logo { ..., alt },\n    description,\n    website\n  }': SPONSORS_QUERY_RESULT;
    '*[_type == "conference"][0].venue->{\n    _id,\n    name,\n    "slug": slug.current,\n    address,\n    description,\n    mapUrl,\n    transitInfo,\n    wifiInfo,\n    image { ..., alt },\n    "rooms": *[_type == "room" && venue._ref == ^._id] | order(order asc, name asc) {\n      _id,\n      name,\n      "slug": slug.current,\n      floor,\n      capacity,\n      amenities\n    }\n  }': VENUE_QUERY_RESULT;
  }
}
